### ISSUE TITLE
Lack of Environment Variables

### ISSUE THREAD

**Issue by Meatballs1** [RCPMAD/RCP_JLP#2]
This should use env vars to locate base directories as not everyone uses C:\ or runs English Windows:

https://github.com/RCPMAD/RCP_JLP/blob/master/RCP_JLP/Program.cs#L91

https://github.com/RCPMAD/RCP_JLP/blob/master/RCP_JLP/Program.cs#L101

e.g. 

`startInfo.WorkingDirectory = "c:\\windows\\system32";`

should use `%windir%\system32`

**Comment by RCPMAD** [comment]
Did not think of other languages. Will test this. Thanks.

**Comment by RCPMAD** [comment]
The correct variables should be the following.

```
%userprofile%\..
%systemroot%\System32
```

Will try them this weekend.

**Comment by RCPMAD** [comment]
This has been fixed now.
